### PR TITLE
Updated rotational broadening method in spectrum.py

### PR DESCRIPTION
**Pull request by cvancil**
Now using rotBroadInt following a discussion about artifacts from pyasl.fastRotBroad appearing in the KPIC DRP. Old method still in spectrum class, not called rotationally_broaden_pyasl

### CODE REVIEW

**Comment by maxwellmb** [comment]
@cvancil, it seems like the np.asscalar function is deprecated and so it's causing some checks to fail. Can you take a look?

**Comment by cvancil** [comment]
This seems to be an incompatibility issue with older versions of astropy and newer versions of numpy. PSISIM currently requires astropy <= 4.2.1 with the note "[need older astropy version until we fix blackbody]." 

I'm using astropy 5.0.4 locally and don't have this numpy issue.

This older version of astropy is used for astropy.modeling.models.BlackBody in telescope.get_thermal_emission(). The new rotational broadening code doesn't interfere with this so the failed tests are because of version control issues.

**Comment by maxwellmb** [comment]
Maybe we require an earlier version of numpy for now then?

**Comment by cvancil** [comment]
Yeah, I'll look into what version we'd need and what issues (if any) this causes.

**Comment by cvancil** [comment]
Not a good fix, most packages require newer versions of numpy so to keep numpy<=1.16 we'd have to restrict versions on all/most of the other required packages. 

astropy.modeling.models.BlackBody and its implementation in PSISIM work for me on astropy 5.2.2, so it seems like allowing current astropy versions would fix the failed tests without breaking the old code unless there is something I missed

**Comment by maxwellmb** [comment]
So, since it sounds like if we remove the astropy version requirement, then we're all in the clear?

**Comment by cvancil** [comment]
Yep! I think so

**Pull request merged**
