### PR TITLE
Throughput updates, PL mode

### PR DESCRIPTION
**Pull request by abgibbs**
-Fixed double counting of fiber coupling dynamic
-Updated echelle row with new values interpolated from blaze function (updated file not contained here, see .zip, but reading modified)
-Added new photonic lantern mode (pl), which provides a throughput boost using Dimitri's function
-Small  cosmetic changes

[Throughput budget.zip](https://github.com/planetarysystemsimager/psisim/files/5152766/Throughput.budget.zip)

### CODE REVIEW

**Comment by maxwellmb** [comment]
@abgibbs, small nitpick, instead of something vague like "pl" can you name the mode "photonic_lantern" or something more descriptive?

**Comment by abgibbs** [comment]
Changed the name!

**Comment by semaphoreP** [comment]
Should we separate the instrument throughput budget file from the telescope one?

**Comment by abgibbs** [comment]
Makes sense, i'll split it.

**Comment by abgibbs** [comment]
[throughput_budgets.zip](https://github.com/planetarysystemsimager/psisim/files/5157663/throughput_budgets.zip)

**Pull request merged**
